[package]
name = "yozuk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bincode = "1.3.3"
boomphf = { version = "0.5.9", features = ["serde"] }
build-info = { version = "0.0.26", features = ["serde"] }
bytes = "1.1.0"
const-sha1 = "0.2.0"
crfs = "0.2.0"
crfsuite = { version = "0.3.1", optional = true }
getrandom = { version = "0.2.5", features = ["js"] }
distance = "0.4.0"
nanoid = "0.4.0"
num_cpus = "1.13.1"
punycode = "0.4.1"
rayon = "1.5.1"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
shell-words = "1.1.0"
slog = "2.7.0"
sloggers = "2.1.1"
yozuk-helper-english = { path = "../helpers/english" }
yozuk-sdk = { path = "../yozuk-sdk" }

yozuk-skill-base64 = { path = "../skills/base64", optional = true }
yozuk-skill-calc = { path = "../skills/calc", optional = true }
yozuk-skill-english = { path = "../skills/english", optional = true }
yozuk-skill-mediatype = { path = "../skills/mediatype", optional = true }
yozuk-skill-numeric = { path = "../skills/numeric", optional = true }
yozuk-skill-smalltalk = { path = "../skills/smalltalk", optional = true }
yozuk-skill-uuid = { path = "../skills/uuid", optional = true }
yozuk-skill-version = { path = "../skills/version", optional = true }
yozuk-skill-lipsum = { path = "../skills/lipsum", optional = true }
yozuk-skill-nanoid = { path = "../skills/nanoid", optional = true }
thiserror = "1.0.30"

[features]
default = [
    "default-skills"
]
modelgen = ["crfsuite", "yozuk-sdk/modelgen"]
default-skills = [
    "yozuk-skill-mediatype", 
    "yozuk-skill-version",
    "yozuk-skill-base64",
    "yozuk-skill-english", 
    "yozuk-skill-smalltalk",
    "yozuk-skill-numeric", 
    "yozuk-skill-calc",
    "yozuk-skill-uuid",
    "yozuk-skill-lipsum",
    "yozuk-skill-nanoid"
]

[build-dependencies]
build-info-build = "0.0.26"
globwalk = "0.8.1"
serde = "1.0.136"
serde_derive = "1.0.136"
toml = "0.5.8"

[dev-dependencies]
lazy_static = "1.4.0"
