[package]
name = "yozuk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bincode = "1.3.3"
boomphf = { version = "0.5.9", features = ["serde"] }
build-info = { version = "0.0.26", features = ["serde"] }
bytes = "1.1.0"
const-sha1 = "0.2.0"
crfs = "0.2.0"
crfsuite = { version = "0.3.1", optional = true }
getrandom = { version = "0.2.5", features = ["js"] }
distance = "0.4.0"
nanoid = "0.4.0"
num_cpus = "1.13.1"
punycode = "0.4.1"
rayon = "1.5.1"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
shell-words = "1.1.0"
slog = "2.7.0"
sloggers = "2.1.1"
thiserror = "1.0.30"
mediatype = "0.19.1"
yozuk-sdk = "0.1.0"
yozuk-helper-english = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0" }

yozuk-skill-base64 = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-calc = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-english = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-mediatype = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-numeric = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-smalltalk = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-uuid = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-version = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-lipsum = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-nanoid = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-punycode = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-dice = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }
yozuk-skill-digest = { git = "https://github.com/yozuk/yozuk", tag = "v0.2.0", optional = true }

[features]
default = [
    "default-skills"
]
modelgen = ["crfsuite"]
default-skills = [
    "yozuk-skill-mediatype", 
    "yozuk-skill-version",
    "yozuk-skill-base64",
    "yozuk-skill-english", 
    "yozuk-skill-smalltalk",
    "yozuk-skill-numeric", 
    "yozuk-skill-calc",
    "yozuk-skill-uuid",
    "yozuk-skill-lipsum",
    "yozuk-skill-nanoid",
    "yozuk-skill-punycode",
    "yozuk-skill-dice",
    "yozuk-skill-digest"
]

[build-dependencies]
build-info-build = "0.0.26"
globwalk = "0.8.1"
serde = "1.0.136"
serde_derive = "1.0.136"
toml = "0.5.8"

[dev-dependencies]
lazy_static = "1.4.0"
