[package]
name = "yozuk-skill-nanoid"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.5", features = ["derive"] }
itertools = "0.10.3"
mediatype = "0.19.1"
nanoid = "0.4.0"
yozuk-helper-english = { path = "../../helpers/english" }
yozuk-sdk = "0.1.0"