[workspace]
members = [
    "yozuk", 
    "yozuk-sdk", 
    "yozuk-bundle",
    "skillset",
    "helpers/*",
    "adapters/*"
]
resolver = "2"

[profile.release]
strip = true

[patch.crates-io]
yozuk-sdk = { path = "./yozuk-sdk" }
yozuk-helper-english = { path = "./helpers/english" }

[patch."https://github.com/yozuk/yozuk"]
yozuk = { path = "./yozuk" }
yozuk-bundle = { path = "./yozuk-bundle" }