[workspace]
members = [
    "yozuk", 
    "yozuk-sdk", 
    "yozuk-bundle",
    "skills/*",
    "helpers/*",
    "adapters/*"
]
resolver = "2"

[profile.release]
strip = true

[patch.crates-io]
slog-stdlog = { git = 'https://github.com/yozuk/stdlog' }