[workspace]
members = [
    "yozuk", 
    "yozuk-sdk", 
    "yozuk-bundle",
    "skills/*",
    "helpers/*",
    "adapters/*"
]
resolver = "2"

[profile.release]
strip = true

[patch.crates-io]
yozuk-sdk = { path = "./yozuk-sdk" }