[package]
name = "yozuk/zuk"
version = "0.22.3"
description = "Yozuk command-line interface"
license = "MIT"
readme = "README.md"
repository = "https://github.com/yozuk/yozuk"
homepage = "https://yozuk.com"

[[module]]
name = "zuk"
source = "target/wasm32-wasi/release/zuk.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "zuk"
module = "zuk"
