[package]
name = "yozuk-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
ascii = "1.0.0"
base64 = "0.13.0"
bytes = { version = "1.1.0", features = ["serde"] }
clap = { version = "3.1.6", features = ["derive"] }
entropy = "0.4.1"
itertools = "0.10.3"
jsonschema = "0.15.0"
mediatype = { version = "0.19.1", features = ["serde"] }
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
shell-words = "1.1.0"
slog = "2.7.0"
sloggers = "2.1.1"

[features]
modelgen = []
