[package]
name = "yozuk-helper-english"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
distance = "0.4.0"
singularize = "0.1.0"
