[package]
name = "yozuk-skill-dice"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
mediatype = "0.19.1"
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8.5"
thiserror = "1.0.30"
yozuk-sdk = { path = "../../yozuk-sdk" }
