name: Cross-Compilation

on:
  push:
    paths:
      - '**.toml'
      - '**.rs'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:    
    strategy:
      matrix:
        toolchain: [arm-linux-androideabi, armv7-linux-androideabi, wasm32-unknown-unknown]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ matrix.toolchain }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      run: rustup target add ${{ matrix.toolchain }}
    - name: Build
      run: cargo build -p yozuk --target=${{ matrix.toolchain }}

  build-macos:
    strategy:
      matrix:
        toolchain: [aarch64-apple-ios]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-${{ matrix.toolchain }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      run: rustup target add ${{ matrix.toolchain }}
    - name: Build
      run: cargo build -p yozuk --target=${{ matrix.toolchain }}
