name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**/Dockerfile'
    - 'images/**'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup/toolchains/stable-*
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install depenedencies
      run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run fmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy --all-features --no-deps
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-features