name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'images/**'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-stable-cargo
    - uses: taiki-e/install-action@nextest
    - name: Run fmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy --all-features
    - name: Run test
      run: cargo nextest run --all-features
    - name: Run test without rayon
      run: cargo nextest run -p yozuk
