name: Rust

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - '**/Dockerfile'
    - 'images/**'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-stable-cargo
    - uses: extractions/setup-just@v1
    - name: Run checks
      run: just check