name: WASI

on:
  push:
    paths-ignore:
    - '**.md'
    - 'images/**'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-stable-wasi-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install wasmtime
      run: curl -sL https://github.com/bytecodealliance/wasmtime/releases/download/v0.37.0/wasmtime-v0.37.0-x86_64-linux.tar.xz | tar Jxv
    - name: Add PATH
      run: echo "$PWD/wasmtime-v0.37.0-x86_64-linux" >> $GITHUB_PATH
    - name: Install cargo-wasi
      run: cargo install cargo-wasi
      continue-on-error: true
    - name: Build
      run: cargo wasi build -p yozuk
    - name: Run test
      run: cargo wasi test -p yozuk
